name: Build Calculus Exam - Semester 1

on:
  push:
    branches: [ master ]
    paths: [ 'src/calculus/sem-1/exam/**' ]

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: 'src/calculus/sem-1/exam/'
          compiler: latexmk
          args: -jobname=calculus-exam-semester-1 -pdf -file-line-error -halt-on-error -interaction=nonstopmode

      - name: Upload pdf document
        uses: actions/upload-artifact@v2
        with:
          name: Calculus Notes - Semester 1
          path: 'src/calculus/sem-1/exam/calculus-exam-semester-1.pdf'
