name: Build Calculus Notes - Semester 1

on:
  push:
    branches: [ master ]
    paths: [ &wd 'src/calculus/sem-1/**' ]

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: *wd
          compiler: latexmk
          args: -jobname=notes-calculus-semester-1 -pdf -file-line-error -halt-on-error -interaction=nonstopmode
